version: '3.8'
services:
  ofelia:
    container_name: ofelia
    image: mcuadros/ofelia:latest
    command: daemon --docker
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - backup-symvol_ofelia-log:/ofelia-log
    labels:
      ofelia.save-folder: "/ofelia-log"
      ofelia.save-only-on-error: "false"
      ofelia.job-local.my-alive-job.schedule: "@every 1h"
      ofelia.job-local.my-alive-job.command: "date"
      ofelia.job-run.print-write-date.schedule: "@every 1h"
      ofelia.job-run.print-write-date.image: "alpine:latest"
      ofelia.job-run.print-write-date.volume: "backup-symvol_portainer-backup:/tmp/test:rw"
      ofelia.job-run.print-write-date.network: "backup-net"
      ofelia.job-run.print-write-date.command: "sh -c 'date | tee -a /tmp/test/date-run'"
    networks:
      backup-net:
volumes:
  backup-symvol_portainer-backup:
    driver: local
    driver_opts:
      device: "/mnt/ext/docker-symvol/portainer-backup"
      type: none
      o: bind
  backup-symvol_ofelia-log:
    driver: local
    driver_opts:
      device: "/mnt/ext/docker-symvol/ofelia-log"
      type: none
      o: bind
networks:
  backup-net:
    name: backup-net
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        # Fixed CIDR
        - subnet: "172.17.1.0/28"
