version: '3.8'
services:
  portainer-backup:
    container_name: portainer-backup
    image: savagesoftware/portainer-backup:latest
    hostname: portainer-backup
    extra_hosts:
      - "portainer:172.17.1.1"
    restart: unless-stopped
    command: schedule
    environment:
      TZ: America/New_York
      PORTAINER_BACKUP_URL: "http://portainer:9002"
      PORTAINER_BACKUP_TOKEN: "ptr_v2u595z/ZiW+ZZ5Z6SpWUf+OXsf2Yan8v5NCRt1F7vQ="
      PORTAINER_BACKUP_PASSWORD: ""
      PORTAINER_BACKUP_OVERWRITE: 1
      PORTAINER_BACKUP_SCHEDULE: "0 5 1 * * *"
      PORTAINER_BACKUP_STACKS: 1
      PORTAINER_BACKUP_DRYRUN: 0
      PORTAINER_BACKUP_CONCISE: 1
      PORTAINER_BACKUP_DIRECTORY: "/backup"
      PORTAINER_BACKUP_FILENAME: "portainer-backup-{{DATE}}.tar.gz"
    volumes:
      - ext_bkp_portainer:/backup
volumes:
  ext_bkp_portainer:
    driver: local
    driver_opts:
      device: "/mnt/extdata/docker-bkp/portainer"
      type: none
      o: bind
networks: 
    bridge: 
          name: bridge
          external: true
