version: '3.8'
services:
  portainer-backup:
    container_name: portainer-backup
    image: savagesoftware/portainer-backup:latest
    hostname: portainer-backup
    extra_hosts:
      - "portainer:172.17.1.1"
    restart: unless-stopped
    command: schedule
    environment:
      TZ: America/New_York
      PORTAINER_BACKUP_URL: "http://portainer:9002"
      PORTAINER_BACKUP_TOKEN: $PORTAINER_BACKUP_TOKEN
      PORTAINER_BACKUP_PASSWORD: ""
      PORTAINER_BACKUP_OVERWRITE: 1
      PORTAINER_BACKUP_SCHEDULE: "0 5 1 * * *"
      PORTAINER_BACKUP_STACKS: 1
      PORTAINER_BACKUP_DRYRUN: 0
      PORTAINER_BACKUP_CONCISE: 1
      PORTAINER_BACKUP_DIRECTORY: "/backup"
      PORTAINER_BACKUP_FILENAME: "portainer-backup-{{DATE}}.tar.gz"
    volumes:
      - ext_bkp_portainer:/backup
    networks:
      backup-net:
  ofelia:
    image: mcuadros/ofelia:latest
    command: daemon --docker
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ext_bkp_ofelia-bin:/ofelia-bin
      - ext_bkp_ofelia-data:/ofelia-data
      - ext_bkp_ofelia-log:/ofelia-log
    labels:
      ofelia.save-folder: "/ofelia-log"
      ofelia.save-only-on-error: "false"
      ofelia.job-local.my-test-job.schedule: "@every 1h"
      ofelia.job-local.my-test-job.command: "date"
    networks:
      backup-net:
volumes:
  ext_bkp_portainer:
    driver: local
    driver_opts:
      device: "/mnt/extdata/docker-bkp/portainer"
      type: none
      o: bind
  ext_bkp_ofelia-bin:
    driver: local
    driver_opts:
      device: "/mnt/extdata/docker-bkp/ofelia-bin"
      type: none
      o: bind
  ext_bkp_ofelia-data:
    driver: local
    driver_opts:
      device: "/mnt/extdata/docker-bkp/ofelia-data"
      type: none
      o: bind
  ext_bkp_ofelia-log:
    driver: local
    driver_opts:
      device: "/mnt/extdata/docker-bkp/ofelia-log"
      type: none
      o: bind
networks:
  backup-net:
    name: backup-net
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        # Fixed CIDR
        - subnet: "172.17.1.0/28"
