version: "3"
services:
  gluetun:
    image: qmcgaw/gluetun
    # container_name: gluetun
    # line above must be uncommented to allow external containers to connect. See https://github.com/qdm12/gluetun/wiki/Connect-a-container-to-gluetun#external-container-to-gluetun
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    ports:
      - 8888:8888/tcp # HTTP proxy
      - 8388:8388/tcp # Shadowsocks
      - 8388:8388/udp # Shadowsocks
      - 8112:8112 # port for deluge
      - 8989:8989 # port for sonarr
      - 7878:7878 # port for radarr
      - 6080:80 # port for lxde
      - 5900:5900 # port for lxde vnc

      - 58846:58846 # deluge remote
    volumes:
      - nas1_config_gluetun:/gluetun
    environment:
      # See https://github.com/qdm12/gluetun/wiki
      - VPN_SERVICE_PROVIDER=ipvanish
      - VPN_TYPE=openvpn
      # OpenVPN:
      - OPENVPN_USER=ss
      - OPENVPN_PASSWORD=ss
      - SERVER_COUNTRIES=Romania
      # Wireguard:
      # - WIREGUARD_PRIVATE_KEY=wOEI9rqqbDwnN8/Bpp22sVz48T71vJ4fYmFWujulwUU=
      # - WIREGUARD_ADDRESSES=10.64.222.21/32
      # Timezone for accurate log times
      - TZ=Etc/UTC
      - HTTPPROXY=off #change to off if you don't wish to enable
      - SHADOWSOCKS=off #change to off if you don't wish to enable
    networks:
      media:
        ipv4_address: "172.17.1.34"
  linuxserver-deluge:
    image: linuxserver/deluge
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
      - DELUGE_LOGLEVEL=error #optional
    volumes:
      - nas1_config_deluge:/config
      - nas1_download:/data-download
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      - gluetun
    networks:
      media:
        ipv4_address: "172.17.1.35"
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - lokal_config_sonarr:/config
      - nas1_download:/data-download
      - nas2_data_tvseries:/data-tvseries
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      - gluetun
    networks:
      media:
        ipv4_address: "172.17.1.36"
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    environment:
      - PUID=0
      - PGID=0
      - TZ=Etc/UTC
    volumes:
      - lokal_config_radarr:/config
      - nas1_download:/data-download
      - nas2_data_movies:/data-movies
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      - gluetun
    networks:
      media:
        ipv4_address: "172.17.1.37"
  lxde:
    image: dorowu/ubuntu-desktop-lxde-vnc:focal-arm64
    environment:
      - VNC_PASSWORD=momo
    volumes:
      - /dev/shm:/dev/shm
      - nas1_download:/data-download
    network_mode: service:gluetun # run on the vpn network
    depends_on:
      - gluetun
    networks:
      media:
        ipv4_address: "172.17.1.38"

volumes:
  nas1_config_gluetun:
    driver: local
    driver_opts:
      device: "/data/nas1-config/gluetun"
      type: none
      o: bind
  nas1_config_deluge:
    driver: local
    driver_opts:
      device: "/data/nas1-config/deluge"
      type: none
      o: bind
  lokal_config_sonarr:
    driver: local
    driver_opts:
      device: "/data/lokal-config/sonarr"
      type: none
      o: bind
  lokal_config_radarr:
    driver: local
    driver_opts:
      device: "/data/lokal-config/radarr"
      type: none
      o: bind
  nas1_download:
    driver: local
    driver_opts:
      device: "/data/nas1-download"
      type: none
      o: bind
  nas2_data_movies:
    driver: local
    driver_opts:
      device: "/data/nas2-data/movies"
      type: none
      o: bind
  nas2_data_tvseries:
    driver: local
    driver_opts:
      device: "/data/nas2-data/tvseries"
      type: none
      o: bind

networks:
  media:
    driver: bridge
    enable_ipv6: false
    ipam:
      config:
        # Fixed CIDR
        - subnet: "172.17.1.32/28"
